### ISSUE TITLE
Run the App on a Physical Phone

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/BookSearch#11]
**Describe the feature and documentation request**
Figure out how to run the mobile app on a physical phone. It should work without an android emulator. The IP address, `10.0.2.2`, only works for the android emulator. Write documentation on running the mobile app on a physical phone.

## Tasks
- [x] Write documentation for running the mobile app on a physical Android phone
- [x] Update the screenshot of the app on my phone
- [x] Create a variable called `SERVER_URL` in the `config.js` file in order to easily update the server URL for the app.

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 11-run-the-app-on-a-physical-phone
```
