### ISSUE TITLE
Display Cover Image

### ISSUE THREAD

**Issue by sagedemage** [sagedemage/BookSearch#31]
**Describe the feature request**
The mobile app should be able to display the cover image of the books.

## Tasks
- [x] Display book cover on the ViewBooks component
  - **Screen name**: Books
- [x] Display book cover on the ViewBooksByAuthor compoent
  - **Screen name**: Author
- [x] Display book cover on the ViewBooksBySubject compoent
  - **Screen name**: Subject
- [x] Update the look of displaying the books 
- [x] Update the screenshot of the current state of the mobile app

## Example
Query for the Pet Sematary books 
https://openlibrary.org/search.json?q=the%20pet%20sematary

```
{
    edition_key: ["OL2389989M"]
    isbn: ["0805775129"]
}
```
Using **edition_key**:
http://covers.openlibrary.org/b/olid/OL2389989M-S.jpg

Using **isbn**:
http://covers.openlibrary.org/b/isbn/0805775129-S.jpg

Resources:
- https://openlibrary.org/dev/docs/api/covers?m=view&v=4
- https://reactnative.dev/docs/image

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 31-display-cover-image
```
